# Configuración para Azure App Service Linux
# Este archivo será útil para configuraciones específicas de Linux
location / {
    try_files $uri $uri/ /index.html;
}

# Configuración de cabeceras de seguridad
add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Configuración de MIME types
location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
}

# Configuración para archivos JSON
location ~* \.json$ {
    add_header Content-Type "application/json";
}
